version: '3.1'
services:
  postgres:
    image: postgres:12
    container_name: superchat-postgres-db-only
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superchat
